# Generated by Django 3.0 on 2019-01-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('faceimage', models.ImageField(upload_to='face')),
                ('lasttime', models.DateField()),
            ],
        ),
    ]
